repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: ["--fix", "lf"]
      - id: trailing-whitespace
        exclude: .bumpversion.cfg
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: name-tests-test
        args: ["--pytest-test-first"]
      - id: requirements-txt-fixer
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.5.0
    hooks:
      - id: docformatter
        args: ["--in-place", "--config", "./pyproject.toml"]
  - repo: https://github.com/PyCQA/autoflake
    rev: v1.7.8
    hooks:
      - id: autoflake
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--ignore-init-module-imports",
          ]
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        entry: black
        require_serial: true
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        additional_dependencies: [".[toml]"]
        args: ["--config", ".pydocstyle.ini"]
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
