[variables.meta.wind_speed]
name = "wind_speed"
standard_name = "wind_speed"
long_name = "Wind speed"
units = "m.s^-1"

[variables.meta.wind_direction]
name = "wind_direction"
standard_name = "wind_to_direction"
long_name = "Wind direction"
units = "degree"

[variables.meta.relative_humidity]
name = "relative_humidity"
standard_name = "relative_humidity"
long_name = "Relative humidity"
units = "%"

[variables.meta.pressure]
name = "pressure"
standard_name = "surface_air_pressure"
long_name = "Atmospheric air pressure"
units = "hPa"

[variables.meta.precipitation_rate]
name = "precipitation_rate"
standard_name = "lwe_precipitation_rate"
long_name = "Precipitation rate"
units = "mm.h^-1"

[variables.meta.air_temperature]
name = "air_temperature"
standard_name = "air_temperature"
long_name = "Air temperature"
units = "Celsius"

[coords.meta.time]
name = "time"
standard_name = "time"
long_name = "Date"
units = "seconds since 1970-01-01"
calendar = "standard"

[attrs]
title = ""
summary = ""
keywords = "GCMD: ATMOSPHERE,GCMD: AEROSOLS,GCMD: AIR QUALITY,GCMD: ATMOSPHERIC PRESSURE,GCMD:  LAND SURFACE/AGRICULTURE INDICATORS,GCMD: ATMOSPHERIC RADIATION,GCMD: ATMOSPHERIC TEMPERATURE,GCMD: ATMOSPHERIC WATER VAPOR,GCMD: ATMOSPHERIC WINDS,GCMD: CLOUDS,GCMD: PRECIPITATION,GCMD: DATA ANALYSIS AND VISUALIZATION,GCMD: CALIBRATION/VALIDATION,GCMD: DATA ANALYSIS,GCMD: STATISTICAL APPLICATIONS"
keywords_vocabulary = "GCMD"
Conventions = "CF-1.8, ACDD-1.3, ISO 8601"
naming_authority = "ACTRIS CCRES"
source = "ACTRIS-EU,ACTRIS CCRES"
comment = ""
acknowledgement = ""
license = ""
standard_name_vocabulary = "CF Standard Name Table v76"
creator_name = "CLU"
creator_type = "Data center"
creator_url = "https://www.aeris-data.fr/"
institution = "CLU"
project = "ACTRIS-CCRES"
program = "ACTRIS-FR"
references = ""
publisher_name = "CLU"
publisher_type = "Institution"
publisher_url = "https://cloudnet.fmi.fi/"
processing_level = "L1"
metadata_link = "https://cloudnet.fmi.fi/"
contributor_name = "CLU,ACTRIS"
contributor_role = "CLU is the data center, ACTRIS is Aerosol, Clouds and Trace Gases Research Infrastructure"
instrument = "GCMD: In Situ/Laboratory Instruments,GCMD: Current/Wind Meters,GCMD: SONIC ANEMOMETER,GCMD: ANEMOMETERS,GCMD: EDDY CORRELATION DEVICES,GCMD: Gauges,GCMD: RAIN GAUGES,GCMD: Photon/Optical Detectors,GCMD: Pressure/Height Meters,GCMD: Probes,GCMD: SOIL MOISTURE PROBE,GCMD: TEMPERATURE PROBES,GCMD: Profilers/Sounders,GCMD: Radiation Sensors,GCMD: Temperature/Humidity Sensors,GCMD: Scatterometers,GCMD: Passive Remote Sensing,GCMD: Active Remote Sensing,GCMD: Photon/Optical Detectors,GCMD: Profilers/Sounders"
instrument_vocabulary = "GCMD"
